export { default as erc6551RegistryAbi } from "./erc6551Registry/abi.json"
export { default as erc6551RegistryAddress } from "./erc6551Registry/address.json"
export { default as simpleUserAccountAbi } from "./simpleUserAccount/abi.json"
export { default as subProfileFactoryAbi } from "./subProfileFactory/abi.json"
export { default as subProfileFactoryAddress } from "./subProfileFactory/address.json"
export { default as subProfileTBAAbi } from "./subProfileTBA/abi.json"
export { default as subProfileTBAAddress } from "./subProfileTBA/address.json"
export { default as userAccountFactoryAbi } from "./userAccountFactory/abi.json"
export { default as userAccountFactoryAddress } from "./userAccountFactory/address.json"
export { default as testNFTAddress1 } from "./testNFT1/address.json"
export { default as testNFTAbi1} from "./testNFT1/abi.json"
export { default as testNFTAddress2 } from "./testNFT2/address.json"
export { default as testNFTAbi2} from "./testNFT2/abi.json"